name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/auth-with-obo

    - name: Build BackendService
      run: dotnet build --configuration Release BackendService/BackendService.csproj
      working-directory: src/auth-with-obo

    - name: Build IntegratingService
      run: dotnet build --configuration Release IntegratingService/IntegratingService.csproj
      working-directory: src/auth-with-obo

    - name: Publish BackendService
      run: dotnet publish --configuration Release --output ./publish/BackendService BackendService/BackendService.csproj
      working-directory: src/auth-with-obo

    - name: Publish IntegratingService
      run: dotnet publish --configuration Release --output ./publish/IntegratingService IntegratingService/IntegratingService.csproj
      working-directory: src/auth-with-obo

    - name: Deploy BackendService to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: backendServiceApp
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: src/auth-with-obo/publish/BackendService

    - name: Deploy IntegratingService to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: integratingServiceApp
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_INTEGRATING }}
        package: src/auth-with-obo/publish/IntegratingService